#!/bin/sh
EXPECTED_ARGS=1

if [ $# -lt $EXPECTED_ARGS ]; then
    echo "Usage: `basename $0`"
    exit 0
fi

myvar=$1
if [ ${#myvar} -eq 2 ]; then
	echo "input size is 2 - deleting sim$1"
	rm sim$1
fi

#rm sim($1)
make sim$1
#CUDA_VISIBLE_DEVICES=0 ./sim$1
CUDA_VISIBLE_DEVICES=1 ./sim$1